export const TODO_CREATE_NEW_TASK = "TODO_CREATE_NEW_TASK";
export const TODO_DELETE_TASK = "TODO_DELETE_TASK";
export const TODO_ON_CLICK_TASK_DONE = "TODO_ON_CLICK_TASK_DONE";
export const TODO_SET_FILTER = "TODO_SET_FILTER";
export const TODO_SET_SEARCH_PATTERN = "TODO_SET_SEARCH_PATTERN";
